# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bUwmupeV2sg-Q8ejJlhW4KqrEpkJ9Tdz
"""

import pandas as pd

# Load dataset
df = pd.read_csv("airline_route_profitability.csv")

# -------------------------------
# 1. Basic overview
# -------------------------------
print(df.head())
print(df.info())

# -------------------------------
# 2. Data cleaning
# -------------------------------
df = df.drop_duplicates()

# Fill missing values (numeric only)
for col in df.select_dtypes(include='number').columns:
    df[col] = df[col].fillna(df[col].median())

# -------------------------------
# 3. Feature engineering
# -------------------------------
# Example: profit margin (adjust column names if needed)
if 'revenue' in df.columns and 'cost' in df.columns:
    df['profit'] = df['revenue'] - df['cost']
    df['profit_margin'] = (df['profit'] / df['revenue']) * 100

# -------------------------------
# 4. Route-level analysis
# -------------------------------
if 'route' in df.columns:
    summary = df.groupby('route').agg(
        total_revenue=('revenue', 'sum'),
        total_cost=('cost', 'sum'),
        avg_profit_margin=('profit_margin', 'mean')
    ).reset_index()

    print("Route Summary:")
    print(summary.head())

# -------------------------------
# 5. Top profitable routes
# -------------------------------
if 'profit' in df.columns:
    top_routes = df.sort_values(by='profit', ascending=False).head(10)
    print("Top Profitable Routes:")
    print(top_routes)

# -------------------------------
# 6. Insight
# -------------------------------
print("Insight:")
print("Routes with higher revenue but controlled costs show better profitability.")